# Generated by Django 3.0.7 on 2020-06-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='caption',
            new_name='description',
        ),
    ]
